(define (make-monitored f)
  (let ((count 0))
    (lambda (arg)
      (cond ((eq? arg 'how-many-calls?) count)
            ((eq? arg 'reset-count)
              (begin (set! count 0)
                     count))
            (else
              (begin (set! count (+ count 1))
                     (f arg)))))))

(define s (make-monitored sqrt))
(print (s 100))
(print (s 144))
(print (s 'how-many-calls?))
(s 'reset-count)
(print (s 'how-many-calls?))
