(define (call-the-cops) (print "Call the cops!!"))

(define (make-account balance password)
  (let ((misscount 0))
    (define (withdraw amount)
      (if (>= balance amount)
        (begin (set! balance (- balance amount))
               balance)
        "Insufficient funds"))
    (define (deposit amount)
      (set! balance (+ balance amount))
      balance)
    (define (dispatch pass m)
      (if (eq? pass password)
        (begin (set! misscount 0)
          (cond ((eq? m 'withdraw) withdraw)
                ((eq? m 'deposit) deposit)
                (else (error "Unknown request : MAKE-ACCOUNT"
                             m))))
        (lambda (arg)
          (set! misscount (+ 1 misscount))
          (begin
            (if (<= 7 misscount)
                  (begin
                    (call-the-cops)
                    "Call the cops!")
                "Insufficient password")))))
    dispatch))

(define acc (make-account 100 'pass))
(print ((acc 'pass 'withdraw) 50))
(print ((acc 'passd 'deposit) 30))
(print ((acc 'passd 'deposit) 30))
(print ((acc 'passd 'deposit) 30))
(print ((acc 'passd 'deposit) 30))
(print ((acc 'passd 'deposit) 30))
(print ((acc 'passd 'deposit) 30))
(print ((acc 'passd 'deposit) 30))
(print ((acc 'passd 'deposit) 30))
(print ((acc 'pass 'withdraw) 100))
(print ((acc 'passd 'deposit) 30))
(print ((acc 'passd 'deposit) 30))
(print ((acc 'pass 'withdraw) 50))
