(define (make-withdraw balance)
  (lambda (amount)
    (if (>= balance amount)
      (begin (set! balance (- balance amount))
             balance)
      "Insufficient funds")))

(define W1 (make-withdraw 100))
(define W2 (make-withdraw 100))

(print (W1 50))
(print (W2 20))
(print (W1 50))
(print (W2 10))
(print (W1 50))
(print (W2 20))
